/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-marchMadness-H8IPrbh8jJ4bT21o2rJn7wg6Ekeo86uH",
  "version": "2020-11-20"
}

export default ebconfig;